steps:
  - name: 'gcr.io/$PROJECT_ID/scala-sbt'
    args: ['test', 'assembly']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/transaction-api', '.']
images: ['gcr.io/$PROJECT_ID/transaction-api']