steps:
  - name: 'gcr.io/$PROJECT_ID/scala-sbt'
    args: ['test', 'assembly']
    id: SbtBuild
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/transaction-api', '.']
    id: DockerBuild
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - transaction-api
      - '--platform=managed'
      - '--image=gcr.io/$PROJECT_ID/transaction-api/transaction-api:latest'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images: ['gcr.io/$PROJECT_ID/transaction-api']